# Generated by Django 3.2.9 on 2021-12-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0010_auto_20211201_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'location Published'},
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.ManyToManyField(null=True, to='book_outlet.Location'),
        ),
    ]
